[toolchain]
anchor_version = "1.1.2"
solana_version = "3.1.10"

[features]
resolution = true
skip-lint = false

[programs.localnet]
movx_coach_pass = "DfpqcSwSer4MrPehwFk2Jota3yJVhqobWWD2Aq1crARB"

[provider]
cluster = "Localnet"
wallet = ".anchor/local-wallet.json"

[scripts]
test = "cargo test -p movx-coach-pass"
