[toolchain]
anchor_version = "1.1.2"
solana_version = "3.1.10"

[features]
resolution = true
skip-lint = false

[programs.localnet]
movx_membership_card = "GEUMk7SoYEsAvTgbFxohHTPbDfdX1citFT6Xxr6E4ULr"

[provider]
cluster = "Localnet"
wallet = ".anchor/local-wallet.json"

[scripts]
test = "cargo test -p movx-membership-card"
